### ISSUE TITLE
Is your limerick missing a license?

### ISSUE THREAD

**Issue by alexgenaud** [MRWilliamsGit/Limerickly#1]
(c) 2022 Maria R Williams

    Permission is granted hereby,
    to copy, share, use, modify,
       for purposes any,
       free or for money,
    provided these rhymes all multiply.

    This work ‘as-is’ I provide.
    No warranty express or implied.
       For no purpose fit,
       not even a wee bit.
    Liability for damages denied.

**Comment by MRWilliamsGit** [comment]
Oh man that's cute! No, there's no license because it doesn't work yet, but it will get there :)
